#re-create errors
#FileExitError
fp=open('data.csv','x')

print(fp)
fp.close()